spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: sbwbss-mvc-local
  port : 8080
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
         
server:
  title: sbwbss-mvc-prod
  port : 8081

 