spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache: false
  h2:
    console:
    enabled: true
    path: /h2-console
  jpa:
    hibernate:
    ddl-auto: create
    generate-ddl: true
    
server:
  error:
    whitelabel:
      enabled: false

  
  
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: c:\\videoServer\\upload\\
      max-file-size: 100MB
      max-request-size: 100MB
      
server:
  title: sbwbss-mvc-local
  port : 8080
  
video:
  uploadPath: c:\\videoServer\\upload\\
  ffmpegPath:  c:\\ffmpeg\\ffmpeg
  ffprobePath: c:\\ffmpeg\\ffprobe
  fontPath: c\:\/ffmpeg\/font\/BMEuljiro10yearslater.ttf
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: /home/users/djna/jar/videoServer/upload/
      max-file-size: 100MB
      max-request-size: 100MB
         
server:
  title: sbwbss-mvc-prod
  port : 8080
  
video:
  uploadPath: /home/users/djna/jar/videoServer/upload/
  ffmpegPath:  /home/users/djna/jar/videoServer/ffmpeg/ffmpeg
  ffprobePath: /home/users/djna/jar/videoServer/ffmpeg/ffprobe
  fontPath: /home/users/djna/jar/videoServer/ffmpeg/font/BMEuljiro10yearslater.ttf