spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: c:\\videoServer\\upload\\
      max-file-size: 100MB
      max-request-size: 100MB
      
video:
  uploadPath: c:\\videoServer\\upload\\
  ffmpegPath:  c:\\ffmpeg\\ffmpeg
  ffprobePath: c:\\ffmpeg\\ffprobe  
  
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: sbwbss-mvc-local
  port : 8080
  
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
         
server:
  title: sbwbss-mvc-prod
  port : 8081

 